Neos:
  Flow:
    resource:
      targets:
        localWebDirectoryPersistentResourcesTarget:
          target: 'Shel\AssetNames\ResourceManagement\Target\FileSystemSymlinkTarget'

Shel:
  AssetNames:
    enabled: true
    expression: "${asset.title + '-' + width + 'x' + height}"
